version: '3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
  web:
    command: python3 manage.py runserver 0.0.0.0:8000
    image: djangoapi
    volumes:
      - .:/code
    ports:
       - "8000:8000"
    depends_on:
      - db
